<a href="https://colab.research.google.com/github/ravulateja/weather-prediction-using-naive-bayies/blob/main/weather_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [22]:
data=pd.read_csv("/content/weather_forecast_data.csv")
data

Temperature   Humidity  Wind_Speed  Cloud_Cover     Pressure     Rain
0       23.720338  89.592641    7.335604    50.501694  1032.378759     rain
1       27.879734  46.489704    5.952484     4.990053   992.614190  no rain
2       25.069084  83.072843    1.371992    14.855784  1007.231620  no rain
3       23.622080  74.367758    7.050551    67.255282   982.632013     rain
4       20.591370  96.858822    4.643921    47.676444   980.825142  no rain
...           ...        ...         ...          ...          ...      ...
2495    21.791602  45.270902   11.807192    55.044682  1017.686181  no rain
2496    27.558479  46.481744   10.884915    39.715133  1008.590961  no rain
2497    28.108274  43.817178    2.897128    75.842952   999.119187  no rain
2498    14.789275  57.908105    2.374717     2.378743  1046.501875  no rain
2499    26.554356  97.101517   18.563084    81.357508  1001.729176  no rain

[2500 rows x 6 columns]

In [23]:
X=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [53]:

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)


print(y)

[1 0 0 ... 0 0 0]


In [54]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)
print(X)
print(y)

[[ 0.1554307   1.26539348 -0.44481385  0.02897213  0.8947143 ]
 [ 0.72322527 -0.89507374 -0.6841429  -1.53407371 -1.07457032]
 [ 0.33954662  0.93859882 -1.47673073 -1.19524633 -0.35066253]
 ...
 [ 0.75442305 -1.0290299  -1.21282806  0.89928899 -0.75241945]
 [-1.0637386  -0.32274425 -1.3032236  -1.6237562   1.59414185]
 [ 0.54229936  1.64176416  1.49793905  1.08868017 -0.62316338]]
[1 0 0 ... 0 0 0]


In [55]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)


In [56]:
from sklearn.naive_bayes import GaussianNB
cla=GaussianNB()
cla.fit(X_train,y_train)

GaussianNB()

In [57]:
x_pred=cla.predict(X_test)


In [63]:
cla.predict([[0,1,0,0,0]])
print(cla.score(X_test,y_test))

0.954
